### ISSUE TITLE
enquiry about libsumo importError

### ISSUE THREAD

**Issue by cherryh2021** [bmetrafficlab/EGO-centric-SUMO#1]
I create a virtual environment of 3.9 and install the packages in the requirement. When I run simulate_town_cosim.py, it says:

Traceback (most recent call last):
  File "d:\research\Macro_and_micro_co-simulation\EGO-centric-SUMO-main\EGO-centric-SUMO-main\simulate_town_cosim.py", line 5, in <module>
    from libsumo_parallel import *
  File "d:\research\Macro_and_micro_co-simulation\EGO-centric-SUMO-main\EGO-centric-SUMO-main\libsumo_parallel.py", line 8, in <module>
    import libsumo
  File "E:\SUMO\tools\libsumo\__init__.py", line 30, in <module>
    from .libsumo import vehicle, simulation, person, trafficlight  # noqa
  File "E:\SUMO\tools\libsumo\libsumo.py", line 13, in <module>
    from . import _libsumo
ImportError: DLL load failed while importing _libsumo: The specified module could not be found.

How can this be fixed? Thank you.

**Comment by bva-bme** [comment]
Dear Xingyi He,

Depending on your operating system, you might have to take some additional steps to make it work. Please see 
https://sumo.dlr.de/docs/Libsumo.html#building_and_installing_it

BR,
 Balázs Varga
